In [318]:
#task:

In [320]:
#1.create a friends names.csv file (delimiter:,)

In [322]:
import pandas as pd

In [324]:
#read_csv()

In [326]:
#read_csv("path",header=,sep=)

In [328]:
df_csv=pd.read_csv(r"C:\Users\hp\salomi\friend_names.csv file.txt",sep=",")

In [330]:
df_csv

  friendname      quality
0   maneesha     creative
1     sujana         kind
2     pushpa        funny
3   Priyanka        smart
4    eliazer  hardworking
5    esterbi        loyal
6     Vijaya       caring
7    Prakash      helpful
8       vani       honest
9   bhargavi     friendly

In [334]:
df_csv.shape

(10, 2)

In [332]:
df_csv.columns

Index(['friendname', 'quality'], dtype='object')

In [336]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   friendname  10 non-null     object
 1   quality     10 non-null     object
dtypes: object(2)
memory usage: 292.0+ bytes

In [338]:
df_csv.describe()

       friendname   quality
count          10        10
unique         10        10
top      maneesha  creative
freq            1         1

In [340]:
#2.create afamily_members.txt file

In [342]:
df_csv=pd.read_csv(r"C:\Users\hp\salomi\family_members.txt file.txt",sep="*")

In [344]:
df_csv

   familymembername          relation
0          jayapaul            father
1     rangasarojini            mother
2        rajakumari      eldestsister
3  venkataramanayya   bigbrotherinlaw
4            mahima             niece
5         sunilraju           brother
6           meghana     sister_in_law
7       yonafrancis            nephew
8          sowjanya      middlesister
9         anilkumar      brotherinlaw

In [346]:
df_csv.shape

(10, 2)

In [348]:
df_csv.columns

Index(['familymembername', 'relation'], dtype='object')

In [350]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   familymembername  10 non-null     object
 1   relation          10 non-null     object
dtypes: object(2)
memory usage: 292.0+ bytes

In [352]:
df_csv.describe()

       familymembername relation
count                10       10
unique               10       10
top            jayapaul   father
freq                  1        1

In [354]:
#3.crate a vegfood_items.txt file (delimiter:|)

In [356]:
df=pd.read_csv(r"C:\Users\hp\salomi\vegfood_names.psv file.txt",sep="|")

In [358]:
df

            vegfoodname     taste
0  paneer butter masala     spicy
1             dal tadka    savory
2          palak paneer      mild
3             aloo gobi     spicy
4           masala dosa     tangy
5     vegetable biryani  fragrant
6         chole bhature     spicy
7          Malaki kofta     sweet
8       gobi manchurian     spicy
9       mixed veg curry    savory

In [362]:
df.shape

(10, 2)

In [364]:
df.columns

Index(['vegfoodname', 'taste'], dtype='object')

In [366]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   vegfoodname  10 non-null     object
 1   taste        10 non-null     object
dtypes: object(2)
memory usage: 292.0+ bytes

In [368]:
df.describe()

                 vegfoodname  taste
count                     10     10
unique                    10      6
top     paneer butter masala  spicy
freq                       1      4

In [370]:
#4.create a nonvegfood_items.txt file (delimiter:|)

In [372]:
df=pd.read_csv(r"C:\Users\hp\salomi\nonvegfood_items.txt file.txt",sep="|")

In [374]:
df

     nonvegfoodname    taste
0   chicken biryani    spicy
1          fish fry   crispy
2      mutton curry     rich
3    butter chicken   creamy
4         egg roast    tangy
5      prawn masala   savory
6      grilled fish    smoky
7        chicken 65      hot
8       keema matar    spicy
9  tandoori chicken  charred

In [376]:
df.shape

(10, 2)

In [378]:
df.columns

Index(['nonvegfoodname', 'taste'], dtype='object')

In [380]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   nonvegfoodname  10 non-null     object
 1   taste           10 non-null     object
dtypes: object(2)
memory usage: 292.0+ bytes

In [382]:
df.describe()

         nonvegfoodname  taste
count                10     10
unique               10      9
top     chicken biryani  spicy
freq                  1      2

In [384]:
#5.create a month_names.txt file (delimiter:&)

In [386]:
df=pd.read_csv(r"C:\Users\hp\salomi\month_names.txt file.txt",sep="&")

In [388]:
df

   monthname      season
0    january      winter
1   february      winter
2      march      spring
3      april      spring
4        may      summer
5       june      summer
6       july     monsoon
7     august     monsoon
8   septmber      autumn
9    October      autumn
10  november  pre-winter
11  december      winter

In [390]:
df.shape

(12, 2)

In [392]:
df.columns

Index(['monthname', 'season'], dtype='object')

In [394]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   monthname  12 non-null     object
 1   season     12 non-null     object
dtypes: object(2)
memory usage: 324.0+ bytes

In [396]:
df.describe()

       monthname  season
count         12      12
unique        12       6
top      january  winter
freq           1       3

In [398]:
#6.colurs_names.txt file (delimiter:^)

In [400]:
df=pd.read_csv(r"C:\Users\hp\salomi\colours_names.txt file.txt",sep="^")

In [402]:
df

   colourname_in_english colourname_in_hindi colourname_in_telugu
0                    red                 lal                erupu
1                   blue               neela               neelam
2                  green                hara            akupachha
3                 yellow               peela               pasupu
4                  white               safed               telupu
5                  black                kala              nallapu
6                   pink              gulabi               gulabi
7                 orange             narangi              narangi
8                  brown               bhura              godhuma
9                   grey              sileti             boodidha
10                purple            baingani              vankaya
11                  gold             sunehra              bangaru

In [404]:
df.shape

(12, 3)

In [406]:
df.columns

Index(['colourname_in_english', 'colourname_in_hindi', 'colourname_in_telugu'], dtype='object')

In [408]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   colourname_in_english  12 non-null     object
 1   colourname_in_hindi    12 non-null     object
 2   colourname_in_telugu   12 non-null     object
dtypes: object(3)
memory usage: 420.0+ bytes

In [410]:
df.describe()

       colourname_in_english colourname_in_hindi colourname_in_telugu
count                     12                  12                   12
unique                    12                  12                   12
top                      red                 lal                erupu
freq                       1                   1                    1